- tuning/config/configs.py
- tuning/sft_trainer.py
- tuning/utils/data_type_utils.py
The PR fixes the code to disable flash attention and allows passing torch dtype as an argument
> allows disable flash attn and torch dtype param

- tuning/sft_trainer.py
This PR formats the dataset to add EOS token which is needed for CausalLMs
I have verified that format of dataset generated looks as expected
###Label : complaint<|endoftext|><pad>.....
> add EOS token to dataset

- .github/workflows/format.yml
- scripts/run_inference.py
- setup.py
- tuning/aim_loader.py
- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/config_utils.py
- tuning/utils/data_type_utils.py
- Adds a GitHub workflow so formatter called when commit pushed
- Adds changes after run of the formatters
Closes #8 
Follow on from #31
> Enable code formatting

- build/Dockerfile
- build/launch_training.py
- scripts/run_inference.py
- setup.py
- tests/utils/test_data_type_utils.py
- tuning/__init__.py
- tuning/aim_loader.py
- tuning/config/__init__.py
- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/data/__init__.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/__init__.py
- tuning/utils/config_utils.py
- tuning/utils/data_type_utils.py
- tuning/utils/merge_model_utils.py
> Adding copyright notices

- CONTRIBUTING.md
Adds instructions to run lint, test, and formatting
Closes #78
Run `make test` and make sure there no error.
> Document lint

- build/Dockerfile
- build/launch_training.py
- scripts/run_inference.py
- setup.py
- tests/__init__.py
- tests/data/__init__.py
- tests/helpers.py
- tests/test_sft_trainer.py
- tests/utils/test_data_type_utils.py
- tuning/__init__.py
- tuning/aim_loader.py
- tuning/config/__init__.py
- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/data/__init__.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/__init__.py
- tuning/utils/config_utils.py
- tuning/utils/data_type_utils.py
- tuning/utils/merge_model_utils.py
Modify team name in copyright notice to name of project/ org
> Modify copyright notice

- tuning/sft_trainer.py
We are adapting to new API for passing flash attention parameter for transformers library.
Closes #16
> fix: use attn_implementation="flash_attention_2"

- build/accelerate_launch.py
- build/launch_training.py
- build/utils.py
- tests/build/test_utils.py
Refactor accelerate launch args parsing logic out into `build/utils.py` and add unit tests
> Move accelerate launch args parsing

- .github/workflows/image.yaml
- build/Dockerfile
- Change fms-hf-tuning python lib is installed in the Dockerfile
- Add GH action to test image build
May close #70 
```
git clone --single-branch --branch whl-install-dockerfile https://github.com/tedhtchang/fms-hf-tuning.git
cd fms-hf-tuning
docker build --progress=plain -t fms-hf-tuning:dev . -f build/Dockerfile
docker build --build-arg WHEEL_VERSION=0.0.1 --progress=plain -t fms-hf-tuning:0.0.1 . -f build/Dockerfile
```
How to test this image in a KinD cluster
Simply
```bash
curl https://gist.githubusercontent.com/tedhtchang/34335240230d64c6e2ecb5b78d8a8cb0/raw/6c568c7fdc82ed9e344474da5278ec43a6fc788b/kind-e2e-sft-mini.sh | bash
```
- [ x] I have added >=1 unit test(s) for every new method I have added.
- [ x] I have ensured all unit tests pass
> Install whl in Dockerfile

- architecture_records/001-trainer-controller-framework.md
This PR makes some changes to the format of the trainer controller configuration format.
Not applicable.
Not applicable.
This is an ADR document change. We will follow this up with implementation PRs.
> adr: Format change to the trainer controller configuration

- build/launch_training.py
- build/utils.py
- tests/build/test_utils.py
Fixes launch training according to the new tracker api.
> fix: launch_training.py arguments with new tracker api

- architecture_records/001-trainer-controller-framework.md
ADR for documenting the change from `eval` to `simpleeval`.
> A quick explanation for why this is safer than eval, e.g., malicious operations that can be added through eval, but not simpleeval to motivate why we should potentially add a new dependency to support this
On safety, at a high level mainly 2 points:
- `simpleeval` is safer than `eval` because it is a whitelist. It simply doesn't have to support the entirety of the Python language features that `eval` has to.
- `simpleeval` also adds runtime checks (for array multiplication, attribute access, big numbers, etc.) to catch malicious code that bypass the simple regex based checks https://github.com/foundation-model-stack/fms-hf-tuning/blob/74caf85140a112cd9289502b0777baac636adf1d/tuning/trainercontroller/callback.py#L267 and also to …
> docs: ADR for moving from `eval` to `simpleeval` for evaluating trainer controller rules

- build/launch_training.py
- tests/build/test_launch_script.py
Add a .complete file to the output directory when finished training. This is a signal to users who are monitoring the output directory that we are finished writing them model to storage.
> add .complete file to output dir when done

- build/Dockerfile
Moving the dnf update to the end as I noticed it missed at least one package that was later installed.
Removing the old python3.9 items (and dnf) as we're using python3.11 and the legacy python3.9 is causing CVE violations. Attempts at upgrading python3.9 was causing many conflicts.
Closes issue https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/828
I did the following:
First I built the latest image from main to make sure it still had the CVEs... it does.
Then, I went through the following steps to test this PR on my OpenShift Cluster
1.  Clone the PR branch
```
git clone https://github.com/jbusche/fms-hf-tuning -b jb-cve-issue-828
cd fms-hf-tuning
```
2.  Build the image
```
docker build --progress=plain -t fms-hf-tuning:jim-0521-nocves . -f build/Dockerfile
```
3. Push …
> remove unused python39 from dockerfile

- build/Dockerfile
- build/launch_training.py
Switch to multistage build 
Build and run image locally similar to steps in the [docs](https://github.com/foundation-model-stack/fms-hf-tuning/tree/main/build#readme), check tuned model and logs exists in the output directory specified in job config. Additionally also load up the tuned model and run inference on it as an extra measure.
> Switch to multistage dockerfile

- README.md
Updates docs for LoRA on what layers to specify
I checked preview
> Update README.md for Lora modules

- build/accelerate_launch.py
- tests/build/test_launch_script.py
Before we needed to merge the LoRA adapter in order for TGIS to properly load the model. Now that this feature is available in vLLM, we can remove the merging of the LoRA adapter.
Added unit tests to verify the behavior.
> remove merge model for lora tuned adapters

- .github/workflows/coverage.yaml
- tox.ini
Check and report unit test coverage in a GHA but not blocking PRs
> Add test coverage

- README.md
- pyproject.toml
- tuning/config/acceleration_configs/acceleration_framework_config.py
* Fix PyPi publish [error](https://github.com/foundation-model-stack/fms-hf-tuning/actions/runs/9704098440/job/26783637649#step:8:24) caused by [direct url reference](https://github.com/foundation-model-stack/fms-hf-tuning/blob/4334d6c89d7d025d7c35b2e3b246f4c191583072/pyproject.toml#L47-L49)
* Document temporary in  README.md
> Fix PyPi publish error caused by direct url reference

- README.md
- examples/trainercontroller_configs/Readme.md
Usage instructions for the trainer controller framework.
https://github.com/foundation-model-stack/fms-hf-tuning/pull/45
NA
> docs: instructions for using the trainer controller framework

- README.md
The command in the README is wrong.
Run the command for LORA and see the output log messages.
> docs: fix the instructions for running with LORA

- tuning/trackers/tracker_factory.py
Fixes bug in https://github.com/foundation-model-stack/fms-hf-tuning/issues/266
https://github.com/foundation-model-stack/fms-hf-tuning/issues/266
`make test`
> fix: logic for getting tracker config

- README.md
- build/accelerate_launch.py
- build/utils.py
- examples/trainercontroller_configs/Readme.md
- tests/build/test_utils.py
- tests/data/__init__.py
- tests/test_sft_trainer.py
- tests/utils/test_data_utils.py
- tests/utils/test_preprocessing_utils.py
- tuning/sft_trainer.py
- tuning/trackers/tracker_factory.py
- tuning/utils/data_utils.py
- tuning/utils/preprocessing_utils.py
Release v1.1.0
Closes #1135
Yes, tested with rc.1 candidate image.
> Releasev1.1.0

- tuning/sft_trainer.py
FIx for the bug in https://github.com/foundation-model-stack/fms-hf-tuning/issues/285
https://github.com/foundation-model-stack/fms-hf-tuning/issues/285
`make test`
> fix: bug where the logger was not being used properly

- examples/trainercontroller_configs/logging_controller_with_rank.yaml
- tests/test_sft_trainer.py
- tuning/sft_trainer.py
> release: merge set of changes for v1.2.1

- error.log
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/controllermetrics/trainingstate.py
- tuning/trainercontroller/operations/hfcontrols.py
- tuning/trainercontroller/operations/logcontrol.py
- tuning/trainercontroller/operations/operation.py
- tuning/trainercontroller/patience.py
This PR switches the logging module from tranformer logger to python logger.
Closes https://github.com/foundation-model-stack/fms-hf-tuning/issues/194
> feat: Migrating the trainer controller to python logger

- tests/utils/test_merge_model_utils.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/merge_model_utils.py
> fix: get num_added_tokens from resize function

- build/README.md
- build/accelerate_launch.py
- tests/build/test_launch_script.py
Add post processing logic from PR #338 to accelerate launch, with unit tests and documentation
> feat: Add post processing logic to accelerate launch

- README.md
Updating supported models list in main README now that we've switched over to predominantly testing Llama3
> docs: Update Supported Models List in README

- README.md
- pyproject.toml
> chore(release): merge set of changes for v2.1.1

- README.md
> docs: Update supported models

- architecture_records/003-generic-tracker-framework.md
@ashokponkumar please merge this typo fix. thanks :)
> fix: bad name in generic tracker ADR

- README.md
> fix: broken README.md link

- README.md
Update supported fms-hf-tuning version for granite3 models since latest bug fix for tokens resolves quality issues with the model.
> docs: update granite3 model support

- .github/workflows/image.yaml
- README.md
- pyproject.toml
- tests/acceleration/test_acceleration_dataclasses.py
- tests/acceleration/test_acceleration_framework.py
- tests/data/test_data_preprocessing_utils.py
- tests/test_sft_trainer.py
- tuning/config/acceleration_configs/__init__.py
- tuning/config/acceleration_configs/acceleration_framework_config.py
- tuning/config/acceleration_configs/fast_moe.py
- tuning/config/acceleration_configs/utils.py
- tuning/data/data_handlers.py
- tuning/data/data_preprocessing_utils.py
- tuning/data/data_processors.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
release 2.4.0! Plus a couple PRs
> chore(release): merge set of changes for v2.4.0

- README.md
> fix: remove duplicate main_process_port entry

- README.md
- docs/ept.md
Adds documentation on how to use advanced data preprocessing for running EPT with our library.
> docs: Add documentation on how to do EPT runs with our library.

- tests/data/test_data_preprocessing_utils.py
- tuning/data/setup_dataprocessor.py
Enable packing for pretokenized datasts.
> feat: Packing for pretokenised datasets

- docs/advanced-data-preprocessing.md
- tests/artifacts/predefined_data_configs/__init__.py
- tests/artifacts/predefined_data_configs/tokenize_using_handler_and_train.yaml
- tests/data/test_data_handlers.py
- tests/test_sft_trainer.py
- tuning/data/data_handlers.py
For most people truncation of dataset samples was not being respected hence allow a tokenizer handler for people to have direct control over dataset and truncate samples properly by calling out the handler in data config.
> feat: Add tokenizer data handler.

- tuning/data/data_handlers.py
Reported by @YashasviChaurasia that this bug was not hit in unit tests due to this being part of logging.
> fix: data handler to string conversion bug

- tuning/utils/evaluator.py
Allow sum ops in trainer controller control rules.
> feat: add sum op for trainer controller

- tests/data/test_data_preprocessing.py
Two test cases in main failed due to a PR merge. This patch fixes that.
> fix: bug which caused test case failures after PR merge

- pyproject.toml
Doing patch release of 2.7.1 with mamba dependency fix in order to publish pypi package.
> build(deps): install mamba_ssm from package instead of github

- README.md
- docs/advanced-data-preprocessing.md
- docs/offline-data-preprocessing.md
Documentation for using Offline Data Preprocessing.
Issue: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1662
> docs: Offline Data Preprocessing documentation

- README.md
Add debug steps/recommendation for common flash-attn issue
> docs: add flash debug steps to docs

- docs/advanced-data-preprocessing.md
- docs/ept.md
> docs: update the `--data_config` flag to `--data_config_path`

- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/sft_trainer.py
- tuning/trainers/sum_loss_sft_trainer.py
Try to enable loss reduction to sum with hf trainer.
> feat: [experimental] enable sum loss trainer

- tuning/trainers/__init__.py
- tuning/trainers/sum_loss_sft_trainer.py
Add missing `__init__.py` file and header
> fix: add init file and header

- README.md
- docs/advanced-data-preprocessing.md
- tests/data/test_data_preprocessing.py
- tuning/config/acceleration_configs/attention_and_distributed_packing.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
Raises an error if multipack is passed with streaming
[Context](https://github.com/foundation-model-stack/fms-acceleration/issues/87#issuecomment-2382869825)
> fix: multipack and streaming are incompatible

- README.md
- tuning/sft_trainer.py
Reverts foundation-model-stack/fms-hf-tuning#531. Needs to revert the PR as more work on the PR is remaining.
> Revert "fix:Remove use_cache and update ReadMe."

- README.md
Adding models that we have not tested but are the same architecture as models we have tested and are different sizes.
> docs: add addt vision model support

- README.md
- tuning/sft_trainer.py
> chore(release): merge set of changes for v2.8.2

- docs/advanced-data-preprocessing.md
Add docs to avoid common pitfalls while specifying the chat template.
> docs: add instructions on how to correctly specify the chat template

- tuning/data/data_processors.py
- tuning/data/utils.py
Multiple bugs
Fixes https://github.com/foundation-model-stack/fms-hf-tuning/issues/551#issuecomment-2893592398
> fix: issues related to providing 2 datasets with diff types

- README.md
Added a section in the `Tips on Parameters to Set` section of the readme describing the `gradient_checkpointing` feature.
Related to[ Issue #1616](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1616)
Just changes to the readme.
> docs: Added gradient checkpointing to docs

- tests/data/test_data_preprocessing.py
- tuning/data/data_processors.py
- tuning/data/utils.py
This PR refactors the dataset loading logic by **decoupling the concatenation functionality** from the `load_dataset` method from DataPreProcessor Class 
A new dedicated wrapper method for the Hugging Face `datasets.concatenate_datasets` API is written, providing capabilities to support concatenation of:
- **`DatasetDict` and `IterableDatasetDict` objects**, with the requirement that all dictionaries share the **same split keys**.
- In case of Multiple Datapaths,  Datasets are of **same type** (i.e. one of  `Dataset`, `DatasetDict`, `IterableDataset`, `IterableDatasetDict`).
- Use existing test cases loading multiple datasets as lists of `DatasetDict` or `IterableDatasetDict`.
- Verify concatenation raises errors if split keys mismatch or dataset types differ.
- Confirm existing dataset …
> fix: decouple and update concatenate_dataset functionality from load_dataset

- pyproject.toml
Upgrade the`transformers`, `torch` and `accelerate` version for supporting GraniteMoeHybrid architecture support https://github.com/foundation-model-stack/fms-hf-tuning/pull/451.
Closes:
https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1786
https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1779
> chore: Upgrade transformers, torch, and accelerate version

- docs/advanced-data-preprocessing.md
- docs/offline-data-preprocessing.md
- tuning/data/data_config.py
fix docs and remove dead code.
> fix: docs and minor code

- tuning/data/data_handlers.py
fix a typo and make an error more informative in data handlers.
> fix: typo and enhanced warning message for jinja and chat template rendering

- examples/trainercontroller_configs/logging_controller_with_rank.yaml
- tests/test_sft_trainer.py
- tuning/sft_trainer.py
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/controllermetrics/trainingstate.py
- tuning/trainercontroller/operations/logcontrol.py
The final checkpoint written with `--save_model_dir` and `--save_strategy "no"` did not log the checkpoint path. This PR adds a custom event to the trainer controller to handle it.
Closes #577
Using `--save_model_dir` and `--save_strategy "no"` should log a save message with the path.
> feat: TC Event to handle final checkpoint

- docs/offline-data-preprocessing.md
> fix: Update offline-data-preprocessing.md

- README.md
- docs/advanced-data-preprocessing.md
- docs/ept.md
- docs/experiment-tracking.md
- docs/installation.md
- docs/installations.md
- docs/supported-models.md
- docs/training.md
- docs/tuning-techniques.md
Follwing the internal discussion we decided to restructure README into separate sections to make it smaller. This PR converts the README into three different pages making the main README smaller and more readable.
NA
> feat: Restructure README
