- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/sft_trainer.py
- tuning/utils/config_utils.py
As part of first refactor , I have created a function for train which will accept predefined dataclasses as arguments instead of taking all possible parameters. 
This was done for the following reasons:
1. **more readability** - now I know exactly what arguments train function accepts
2. **allows for easier parameter validation  + usability** - since users have to pass either Loraconfig dataclass or promptuning dataclass, they know upfront what parameters are relevant for each type. 
3. **modular code** - rather than having everything in a big main function, we can have train, load and run in future
The main function is reading all arguments from command line and passing relevant params to train() as an example. 
I will move the main() to an example script going forward, and we can …
> First refactor train

- tuning/sft_trainer.py
Now that I am using HF parser the arguments are returned in their own namespace so we need to access them as class objects.
Without this fix, it was always setting tuning config to None and doing Fine tuning
> fix : the way args are passed

- tuning/sft_trainer.py
when peft config is None, we are doing full parameter tuning, in which case the "peft fsdp wrapping" won't be a good wrapping.  And this causes some side issues like nested wrapping, which further caused some weird behaviors and errors.
> fix full param tuning

- tuning/sft_trainer.py
When I install `tuning` and try to run `sft_trainer.train()` from within another python script, I get error
```
Traceback (most recent call last):
File "/app/launch_training.py", line 28, in <module>
from tuning import sft_trainer
File "/usr/local/lib/python3.11/site-packages/tuning/sft_trainer.py", line 13, in <module>
from aim_loader import get_aimstack_callback
ModuleNotFoundError: No module named 'aim_loader'
```
This should fix this error
> fix import of aim_loader

- tuning/sft_trainer.py
Should use the user provided model max length if it valid and below the model's max length. Will also print log message if the user provided one exceeds the model one and both values which is helpful for debugging. Note that `train_args.model_max_length` is set by default to 4096 if the user does not provide a value.
> fix: set model max length to either passed in or tokenizer value

- tuning/sft_trainer.py
Related to #17, upon further testing noticed this bug that sets the `tokenizer.max_model_length` to the one passed in by the user trainer args. Now both are properly separated and value is selected based on min.
> fix: do not set model max length when loading model

- requirements.txt
- tuning/config/peft_config.py
- tuning/sft_trainer.py
- tuning/utils/config_utils.py
> feat: support str in target_modules for LoraConfig

- .github/dependabot.yml
With this PR, [Dependabot](https://dependabot.com/) can automatically scan the dependencies daily and create a PR if there is a newer version of the upstream package is available.
> Enable daily dependabot updates

- tuning/sft_trainer.py
This PR adds a new callback, which is invoked on the logging event - if the most recent log contains specific keys, the subdictionary is extracted, and the `train_loss.json` is reexported.
Example using LLama 7b with the twitter complaints example (tested on single GPU with a v100).
```bash
python tuning/sft_trainer.py  --model_name_or_path $MODEL_PATH  --data_path $DATA_PATH  --output_dir $OUTPUT_PATH  --num_train_epochs 5  --per_device_train_batch_size 4  --per_device_eval_batch_size 4  --gradient_accumulation_steps 4  --evaluation_strategy "no"  --save_strategy "epoch"  --learning_rate 1e-5  --weight_decay 0.  --warmup_ratio 0.03  --lr_scheduler_type "cosine"  --logging_steps 1  --include_tokens_per_second  --packing False  --response_template "\n### Label:"  --peft_method pt …
```
> Add file logger callback & export train loss json file

- tuning/utils/merge_model_utils.py
This PR adds a post-processing utility for merging one or more lora models back into a base model. If multiple lora models are provided, they are combined with equal weights (references supporting that this is what this PR is actually doing are provided in the docstring). An optional flag can be set to also export the tokenizer.
Example usage showing calling the merge util func and reloading + running an inference call with a tiny llama model - I've tried the same to with a llama 7b model to make sure it doesn't explode successfully:
```python
from tuning.utils.merge_model_utils import create_merged_model
save_tokenizer = True
base_model = "TinyLlama/TinyLlama-1.1B-step-50K-105b"
checkpoint_models = ["out/checkpoint-9", "out/checkpoint-13"]
merged_model_id = "my_merged_model" …
```
> Merge models

- tuning/sft_trainer.py
Changes include:
- In addition to the `train_loss.jsonl` file that is outputted, a similar `eval_loss.jsonl` file is also created if eval loss is found in the logs.
- Refactor for reuse of logic for tracking loss
> feat: track validation loss in logs file

- .github/workflows/test.yaml
- tests/utils/test_data_type_utils.py
- tox.ini
- tuning/utils/data_type_utils.py
Changes:
1. Adds unit tests for utilts/data_type_utils module
2. Enables unit test framework in the workflow for every PR
Closes #5
Verify in a virtual env:
```bash
git clone https://github.com/tedhtchang/fms-hf-tuning -b add_sample_unit_test
cd fms-hf-tuning
pip install -r setup_requirement.txt
tox run -e py
```
Should see something like:
```
============================================================================================================================= test session starts ==============================================================================================================================
platform darwin -- Python 3.11.7, pytest-8.0.2, pluggy-1.4.0
cachedir: .tox/py/.pytest_cache
rootdir: /Users/tedchang/pub_git/fms-hf-tuning
collected 3 items …
```
> Add sample unit tests

- .github/workflows/format.yml
- .pylintrc
- build/launch_training.py
- scripts/run_inference.py
- tox.ini
- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/data_type_utils.py
- tuning/utils/merge_model_utils.py
Changes
1. Add pylint to workflow
2. Fix existing pylint errors
Closes #59
Test locally:
git clone https://github.com/tedhtchang/fms-hf-tuning -b Enable-pylint
```bash
cd fms-hf-tuning
pip install -r setup_requirement.txt
tox run -e lint
```
> Enable pylint in the github workflow

- build/launch_training.py
Allow SFT_TRAINER_CONFIG_JSON_ENV_VAR to be encoded json string, not just pickled python
Users of SFT Trainer may be using other programming languages than python to programmatically deploy the job, therefore SFT_TRAINER_CONFIG_JSON_ENV_VAR should not just accept a pickled python object, but also accept just a plain encoded json string.
> Allow SFT_TRAINER_CONFIG_JSON_ENV_VAR to be encoded json string

- tuning/config/configs.py
- tuning/sft_trainer.py
@raghukiran1224 @Ssukriti @anhuong Im suggesting two fixes here
1. We observe failures with newer version of transformers because of a newly added `xla_fsdp_v2` flag here. The current strategy is to manually patch missing flags because `transformers.TrainingArguments.__post_init__` is not called. But this means one has to constantly update the manual patches if there are changes to HF code, which is not ideal.  Huggingface trainer will properly initialize everything based on  `TrainingArguments` (including [gradient checkpointing](https://github.com/huggingface/transformers/blob/2cc8cf6ce7ae0416561acbb639df4bbc5f409b6f/src/transformers/trainer.py#L1749-L1755). 
2. The `PeftSavingCallback` is not the ideal patch now that https://github.com/huggingface/transformers/pull/28297 has been …
> Let Huggingface Properly Initialize Arguments, and Fix FSDP-LORA Checkpoint-Saves and Resumption

- README.md
- examples/prompt_tuning_twitter_complaints/README.md
- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/sft_trainer.py
- update max_model_length to max_seq_length to match sfttrainer input arg
- update data_path to training_data_path to distinguish between training and validation data
- update unit tests and docs with new args
closes: #36
> Update input args to max_seq_length and training_data_path

- README.md
- build/Dockerfile
- pyproject.toml
- requirements.txt
- tuning/aim_loader.py
- tuning/sft_trainer.py
- tuning/utils/import_utils.py
Currently, not setting `--peft_method` defaults to prompt tuning. However, intuitively, not passing --peft_method should mean not to use any parameter efficient method like LoRA and prompt tuning. Therefore, its good to fallback to full parameter tuning rather prompt tuning. PR adds this.
Closes #48 
Yes ✅
```
fmstuning ❯ python sft_trainer.py --output_dir ./output
Namespace(peft_method='none')
```
> fix: not passing PEFT argument should default to full parameter finetuning

- build/Dockerfile
- build/README.md
- build/accelerate_launch.py
- build/launch_training.py
- Adds additional script that parses params for `accelerate launch` which calls original launch_training to support multi (and single) GPU tuning
- Dockerfile changes:
- Add new script and default FSDP config to image
- Give tuning user ownership of /tmp dir - helps with running fms-hf-tuning code
- Update default command to run accelerate launch script
- Update logging messages launch_training
closes: #88 
Tested script running fine tuning on multi-GPU cluster for large models that required loading on multi-GPUs to run. Ran with the default FSDP config provided.
Testing with FSDP, 3 GPUs, FT with granite-13b-instruct-v2' model:
```sh
$ python /app/accelerate_launch.py 
INFO:root:Using multi-GPU configs: {'num_machines': 1, 'num_processes': 3, 'main_process_port': 1234, 'config_file': …
```
> feat: update launch training with accelerate for multi-gpu

- build/Dockerfile
Need to be able to import utils from `build.utils` from the launch_training script. Hit error
```
Traceback (most recent call last):
File "/app/launch_training.py", line 35, in <module>
from build.utils import process_launch_training_args
ModuleNotFoundError: No module named 'build'
Traceback (most recent call last):
File "/app/launch_training.py", line 35, in <module>
from build.utils import process_launch_training_args
ModuleNotFoundError: No module named 'build'
```
Tested this in a new image and it imports successfully.
> add refactored build utils into docker image

- tests/test_sft_trainer.py
- tuning/sft_trainer.py
Combine train and eval logs into single training logs file.
From unit tests, output file looks like:
`training_logs.jsonl`
```json
{"data": {"epoch": 1.0, "step": 1, "timestamp": "2024-04-04T23:22:00.986341", "value": 8.0445}, "name": "training_loss"}
{"data": {"epoch": 1.0, "step": 1, "timestamp": "2024-04-04T23:22:01.377816", "value": 10.59613037109375}, "name": "validation_loss"}
{"data": {"epoch": 2.0, "step": 3, "timestamp": "2024-04-04T23:22:01.985366", "value": 4.015}, "name": "training_loss"}
{"data": {"epoch": 2.0, "step": 3, "timestamp": "2024-04-04T23:22:02.157271", "value": 10.596086502075195}, "name": "validation_loss"}
{"data": {"epoch": 3.0, "step": 5, "timestamp": "2024-04-04T23:22:02.798441", "value": 3.9365}, "name": "training_loss"}
{"data": {"epoch": 3.0, "step": 5, …
```
> feat: combine train and eval loss into one file

- README.md
- tuning/config/peft_config.py
Improvements to README to explain how to pass parameters for tuning techniques
None as small issue
Rendered md
Rendered md and viewed links
> Docs improvements

- build/launch_training.py
- tuning/sft_trainer.py
Bug fix to copy over the training logs file after file was renamed recently.
Built image locally, ran tuning job and verified `training_logs.jsonl` existed in specified `output_dir`
> Copying logs file

- build/launch_training.py
Fix copying over logs when `num_processes>1`
Built new image, ran a sample job on test cluster and checked `training_logs.jsonl` was copied over
> Fix copying over logs

- requirements.txt
- scripts/run_evaluation.py
- scripts/run_inference.py
- Adds a script for model evaluation for generation based classification.
Sample usage is as follows (details can be seen with `--help` - this is is just for the sake of example and illustrates how to run something). Note that `train` is the default split for loading a local file, and the usage of `--split` matches that of a normal HF dataset. A `--delimiter` may also be passed for multi output classification.
```
python3 run_evaluation.py --model TinyLlama/TinyLlama-1.1B-step-50K-105b  --data_path stanford_alpaca/alpaca_data.json  --max_new_tokens 10  --purge_results --split train[:50] --delimiter , 
```
Running an evaluation produces a directory containing 4 files, each of which is shown with an example snippet below.
1. `eval_metrics.json` - contains the metrics themselves.
```json
{ …
```
> Add eval script

- pyproject.toml
- requirements.txt
- tox.ini
- Moves sklearn to optional dev dependencies
- Include optional dev dependencies when linting to avoid pylint import errors on optional dependencies
Run linting and see that the sklearn import does not result in a linting failure.
> Move sklearn to optional, install optionals for linting

- scripts/run_evaluation.py
Fixes a bug introduced by https://github.com/foundation-model-stack/fms-hf-tuning/pull/121 - this should be repeatedly removing the suffix and not (character level) rstripping, nice catch @anhuong
> Fix eos token suffix removal

- tests/data/__init__.py
- tests/data/malformatted_data.json
- tests/test_sft_trainer.py
- tuning/sft_trainer.py
This PR adds some extra unit tests for various edge cases. It also fixes (one of) the edge cases that has validation which is currently unreachable. It also changes a few stray `sys.exit()` calls to just raise errors, since I don't think there's a special reason to have those there at the moment.
NOTE: Some of these tests are testing errors that are thrown by HF libraries for things we don't explicitly validate ourselves to ensure the behavior is stable with version bumps.
This is a follow-up on: https://github.com/foundation-model-stack/fms-hf-tuning/issues/74
We made the decision to split the PR into two parts, to get the tests covering the base functionality it earlier.
> Add unit tests for various edge cases

- .github/workflows/build-and-publish.yaml
fixes a small typo in .github/workflows/build-and-publish.yaml that stops the tox install from working.
Closes https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/774
I did the following
1.  I pushed this PR to my local fork's main branch so that I could publish a new release to PyPI and test
2. Then from there I created a new release and it succeeded with this new change: https://github.com/jbusche/fms-hf-tuning/actions/runs/8824603436/job/24227364778
3. I then used this new release to try to build a local image:  
```
docker build --build-arg WHEEL_VERSION=0.0.1rc7 --progress=plain -t fms-hf-tuning:0.0.1rc7 . -f build/Dockerfile
```
4. Then I pushed it to my local openshift repo:
```
podman login -u kubeadmin -p $(oc whoami -t) $(oc registry info) --tls-verify=false …
```
> fix typo in build gha

- scripts/run_evaluation.py
- scripts/run_inference.py
Add `use_flash_attn` flag for the inference and evaluation scripts. When used, this will load the model using flash attention which can affect the inference results.
related to: #103 
Ran the scripts loading llama-7b model and a Lora tuned llama-7b model that requires merging. Saw that when using flag, the model is loaded with flash attention as noted by the log output.
inference:
```sh
$ python scripts/run_inference.py --model /llama-eval-pvc/LLaMa/models/hf/7B --out_file llama_7b --max_new_tokens 50 --text "Today is a good day. What do you want to do today?" 
No adapter config found! Loading as a merged model...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 2/2 [00:25<00:00, 12.86s/it]
Inferred device: cuda …
```
> feat: add flash attn to inference and eval scripts

- build/Dockerfile
This Dockerfile change does two things:
1.  It does a `dnf update -y` so that we catch the latest fixes that might not yet be in the latest ubi build. For example in this case there are 2 known `libexpat` medium vulnerabilities that this update method closes in our image.
2. This removes a high `Private keys stored in image` issue with `Found: /usr/share/doc/perl-Net-SSLeay/examples/server_key.pem`
Closes issue https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/758
(Note, you need an environment running with Kueue and KFTO)  Otherwise, it might be possible with Kind.
1. Clone the branch to your podman environment
```
git clone https://github.com/jbusche/fms-hf-tuning.git -b jb-issue-758
cd fms-hf-tunin
```
2.  Build the image:
```
docker build -t fms-hf-tuning:issue758-1 …
```
> OS update in dockerfile

- .gitignore
Fixes https://github.com/foundation-model-stack/fms-hf-tuning/issues/141
https://github.com/foundation-model-stack/fms-hf-tuning/issues/141
`make test` or `tox -e build`
> fix: ignore the build output and auto-generated files

- examples/trainercontroller_configs/loss.yaml
- tests/data/trainercontroller/loss_custom_metric.yaml
- tests/data/trainercontroller/loss_custom_operation.yaml
- tests/data/trainercontroller/loss_custom_operation_invalid_action.yaml
- tests/data/trainercontroller/loss_invalid_metric.yaml
- tests/data/trainercontroller/loss_invalid_operation.yaml
- tests/data/trainercontroller/loss_invalid_operation_action.yaml
- tests/data/trainercontroller/loss_invalid_trigger.yaml
- tests/data/trainercontroller/loss_on_threshold.yaml
- tests/data/trainercontroller/loss_with_malicious_input_rule.yaml
- tests/data/trainercontroller/loss_with_malicious_os_rule.yaml
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/operations/operation.py
- tuning/trainercontroller/operations/operations.yaml
Standardized the format in the yaml files used by `TrainerControllerCallback`.
https://github.com/foundation-model-stack/fms-hf-tuning/issues/129
We have tests which can be run with `make test`
Run `make test`
> feat: new format for the controller metrics and operations

- tests/data/trainercontroller/__init__.py
- tests/data/trainercontroller/exposed_metrics.yaml
- tests/data/trainercontroller/incorrect_source_event_exposed_metrics.yaml
- tests/trainercontroller/test_tuning_trainercontroller.py
- tuning/trainercontroller/controllermetrics/__init__.py
- tuning/trainercontroller/controllermetrics/eval_metrics.py
Evaluation metrics could be customized in the hugging face. Using these metrics within the stopping criteria rules of the trainer controller framework will help stop training if the training is not making progress. This PR exposes the evaluation metrics to be used in trainer controller rules.
Closes #136 
Add trainer controller configuration for `eval metrics`.
> feat: Exposed the evaluation metrics for rules within trainer controller

- build/Dockerfile
This comments out the AIM module so that it's not installed.  This has two benefits:
1. As AIM isn't FIPS tolerant yet, it's removal allows the fms-hf-training image to run on a FIPS cluster without errors.
2. The (now) unused AIM module won't be installed and end up potentially causing CVE issues later.
Closes issue [842](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/842)
I built it and ran it using these steps on my OpenShift cluster:
```
git clone https://github.com/jbusche/fms-hf-tuning -b jb-remove-aim-issue842
cd fms-hf-tuning/
docker build --progress=plain -t fms-hf-tuning:jim-0510-noaim . -f build/Dockerfile
podman login -u kubeadmin -p $(oc whoami -t) $(oc registry info) --tls-verify=false
podman tag localhost/fms-hf-tuning:jim-0510-noaim  $(oc registry …
```
> Comment out aim in dockerfile

- pyproject.toml
- tests/data/trainercontroller/__init__.py
- tests/data/trainercontroller/loss_with_invalid_type_rule.yaml
- tests/trainercontroller/test_tuning_trainercontroller.py
- tests/utils/test_evaluator.py
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/control.py
- tuning/utils/evaluator.py
Use the AST module to evaluate the rules instead of `eval`.
1. We use the Python AST library to parse the code.
2. We use this library https://github.com/danthedeckie/simpleeval for traversing and evaluating the generated AST.
3. The output of evaluation should be a boolean value which we return indicating if the rule succeeded.
Example supported expressions: https://github.com/danthedeckie/simpleeval?tab=readme-ov-file#operators
Support for more complex types (list, dict, etc.) are also implemented:
- https://github.com/danthedeckie/simpleeval?tab=readme-ov-file#compound-types
- https://github.com/danthedeckie/simpleeval/blob/2a12b5856d6f70b78dc1ac38840c80c1be6c6c4e/simpleeval.py#L638-L642
Notes:
- PyPi https://pypi.org/project/simpleeval/ (MIT Licence)
- Array Multiplication …
> fix: replace eval with a safer alternative

- build/accelerate_launch.py
- build/launch_training.py
- build/utils.py
- tests/build/test_launch_script.py
- tests/test_launch_script.py
When the tuning code is being launched via `accelerate_launch.py` in a kubernetes environment, we want error messages for failed tuning jobs to be surfaced in the pod status. In order to do this, these scripts must be able to catch all exceptions and write succinct error messages into the `/dev/termination-log`.
> Add exception catching / writing to termination log

- build/launch_training.py
Fixes error in merging lora tuned checkpoint when running on multi-GPU. 
```
File "/app/launch_training.py", line 89, in main
create_merged_model(
File "/usr/local/lib/python3.11/site-packages/tuning/utils/merge_model_utils.py", line 70, in create_merged_model
model = PeftModel.from_pretrained(model, checkpoint_model)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/peft/peft_model.py", line 328, in from_pretrained
PeftConfig._get_peft_type(
File "/usr/local/lib/python3.11/site-packages/peft/config.py", line 203, in _get_peft_type
raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
ValueError: Can't find 'adapter_config.json' at '/tmp/tmppvqpid1c/checkpoint-1670'
```
When running lora tuning on multi-GPU, the tempdir is created …
> fix: merging of model for multi-gpu

- tests/helpers.py
- tests/test_sft_trainer.py
Unit tests for full fine tuning should not have any tuning config set . This PR fixes the unit tests by unsetting the PT config that was getting set for FT 
1. Unit tests pass
2. No adapter_config is created which is how Full fine tuning should be
> tests for fixing full fine tuning

- examples/kfto-kueue-sft-trainer.yaml
Fixes the KFTO example so it is a fully functional test that users can run with. Bloom model can't run with flash-attn set.
> fix: bloom model can't run with flash-attn

- tests/test_sft_trainer.py
- tuning/sft_trainer.py
Fixes a small bug in the method of train() sft_trainer.py where trainer_callbacks would append an array of user provided callbacks instead of concatenating the 2 arrays.
Without this change you get this exception:
```
self = <transformers.trainer_callback.CallbackHandler object at 0x32b558fa0>
event = 'on_init_end'
args = TrainingArguments(output_dir='/var/folders/p_/lhp3_gn503l7djn80tdzkf3h0000gn/T/tmpu2qek8_i', overwrite_output_dir=Fals...t_modules=None, batch_eval_metrics=False, cache_dir=None, max_seq_length=4096, packing=False, trackers=['file_logger'])
state = TrainerState(epoch=None, global_step=0, max_steps=0, logging_steps=500, eval_steps=500, save_steps=500, train_batch_si..., 'should_epoch_stop': False, 'should_save': False, 'should_evaluate': False, 'should_log': False}, …
```
> Fix additional callbacks

- tests/utils/test_preprocessing_utils.py
- tuning/sft_trainer.py
- tuning/utils/preprocessing_utils.py
allows minor refactoring to allow easier integration of pretokenized input and other forms of masking
Changes added:
1. validate_data_args function - validates the JSON formats. Can be further extended to do  any validation for pretokenized datasets can also be done in this function
2. get_data_collator - function to return appropriate data collator as per data format .
1. Related to : https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/991 - gives modules on where to add pretokenized changes
2. first step to allow masking without completion LM
> minor refactor to allow modular functions

- tests/data/trainercontroller/__init__.py
- tests/data/trainercontroller/loss_unavailable_metric.yaml
- tests/trainercontroller/__init__.py
- tests/trainercontroller/custom_metric.py
- tests/trainercontroller/custom_operation.py
- tests/trainercontroller/custom_operation_invalid_action.py
- tests/trainercontroller/test_tuning_trainercontroller.py
- tests/utils/test_evaluator.py
- tuning/trainercontroller/callback.py
- tuning/utils/evaluator.py
Some metrics may not be available at the time of rule evaluation. Add some more unit tests for the same conditions.
Fixes #165 
#165 
`make test`
> feat: support some metrics being 'None' without stopping training

- scripts/run_inference.py
- tests/test_sft_trainer.py
- tests/utils/test_embedding_resize.py
- tuning/config/configs.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
Allow resizing the model's embedding layer to the given multiple after addition of the tokenizer's new tokens for better memory efficiency.
Closes #193
You can use the embedding multiple option readily by passing the argument. 
```
--embedding_size_multiple_of <multiple> # 8 or 64 etc
```
Sample training working and completed uses the `--embedding_size_multiple_of 64` option
Memory usage while training
Difference in memory with a bad multiple `--embedding_size_multiple_of 13`
Saved checkpoints
> Support custom embedding layer resizing to the desired multiple

- README.md
- pyproject.toml
- tuning/config/acceleration_configs/acceleration_framework_config.py
- tuning/config/acceleration_configs/fused_ops_and_kernels.py
- tuning/config/acceleration_configs/quantized_lora_config.py
@tedhtchang @anhuong 
This reintroduces the `fms-acceleration` package, which will soon be available ~once this PR is merged https://github.com/foundation-model-stack/fms-acceleration/pull/45~
- **Update**: the package has been released https://pypi.org/project/fms-acceleration
It also introduces some minor fixes. 
#219 
1. Install and check its properly installed
```
pip install "fms-hf-tuning[fms-accel] @ git+https://github.com/fabianlim/fms-hf-tuning.git@fix/accel-ref"
```
Then verify 
```
Successfully installed fms-acceleration-0.1.0 fms-hf-tuning-0.1.dev208+g3157e6f simpleeval-0.9.13 tokenizers-0.15.2 transformers-4.39.3
```
> ReIntroduce Package for FMS Accel

- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/config/peft_config.py
- tuning/sft_trainer.py
- tuning/utils/config_utils.py
Currently we presume the tokenizer is always available at `model_name_or_path`https://github.com/foundation-model-stack/fms-hf-tuning/blob/b655e1ae6f0e7cf7f93933c0cc2dd72023a8d0f3/tuning/sft_trainer.py#L174. So, the handy solution for this is to simply introduce new argument `tokenizer_name_or_path` in the model arguments https://github.com/foundation-model-stack/fms-hf-tuning/blob/b655e1ae6f0e7cf7f93933c0cc2dd72023a8d0f3/tuning/config/configs.py#L34. However, this isn't the case for us since that argument is already being used in PEFT PT config https://github.com/foundation-model-stack/fms-hf-tuning/blob/b655e1ae6f0e7cf7f93933c0cc2dd72023a8d0f3/tuning/config/peft_config.py#L82
Given the premise, one approach would be to use the argument `tokenizer_name_or_path` from PEFT PT config …
> feat: support custom tokenizer

- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/sft_trainer.py
- tuning/trackers/aimstack_tracker.py
- tuning/trackers/filelogging_tracker.py
- tuning/trackers/tracker_factory.py
Unit tests for the tracker framework.
All unit tests with `aim` tracker installed
```
tests/test_sft_trainer.py::test_run_causallm_pt_and_inference
tests/test_sft_trainer.py::test_run_causallm_pt_and_inference_with_formatting_data
tests/test_sft_trainer.py::test_run_causallm_pt_and_inference_JSON_file_formatter
/Volumes/Projects/Projects/projects/2023/ai-platform-engg/fms-hf-tuning/.tox/py/lib/python3.9/site-packages/peft/peft_model.py:1533: UserWarning: Position ids are not supported for parameter efficient tuning. Ignoring position ids.
warnings.warn("Position ids are not supported for parameter efficient tuning. Ignoring position ids.")
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================= 104 passed, 11 …
```
> tests: tracker unit tests

- tuning/trainercontroller/callback.py
- tuning/trainercontroller/operations/operations.yaml
This pull request moves the defaults for metrics / operations into variables instead of yaml files. The main reason for doing this is for convenience of distribution; the current `build` in the Dockerfile ([here](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/build/Dockerfile#L122)) does *not* bundle the default yaml files into the wheel, which crashes the controller framework upon startup.
There are workarounds in the distribution side, e.g., we could write a `setup.py` to include assets that aren't python files etc, but IMO it makes more sense to just keep the defaults in variables that can be easily found, since the yaml files are only read once at initialization time anyway.
Note that as part of this, we're also changing default metrics to `{}` instead of `None` to …
> Move default operations and metrics to variables

- pyproject.toml
set the transformers version greater than 4.41 as it may have severe performance degradation. (@Ssukriti) 
set upper limit of transformers to 5.0, and removing this version constraint (!=4.38.2)
Fix of #246
> deps: Update transformers lower bound version

- README.md
Link to trainer controller readme broken.
"Closes #253"
Click on the trainer controller readme link in this [section](https://github.com/foundation-model-stack/fms-hf-tuning/tree/main?tab=readme-ov-file#trainer-controller-framework).
> fix: Added correct link in main readme for the trainer-controller readme

- build/accelerate_launch.py
- build/utils.py
- tests/build/test_utils.py
Intended to reproduce the functionality of `shutil.copytree()`, but uses `shutil.copy2()` to get around the problem  `shutil.copytree()` has of trying to modify the directory metadata, which fails on a root NFS directory mounted and owned by root in a SFT tuning pod.
Run a SFT tuning session where the `output_dir` is set to a root owned, everyone writable NFS volume.
Unit tests are not submitted as part of the PR, but can be found [here](https://github.com/olson-ibm/copytree/blob/main/test/test.py). All passed.
Integration tests also completed successfully, can provide the test cases and results upon request.
> Replace shutil.copytree() to fix permission error

- tests/utils/test_config_utils.py
Add unit tests for the config_utils with 100% test coverage
Part of #75
> Add config_utils tests

- examples/trainercontroller_configs/loss.yaml
- tests/data/trainercontroller/loss_custom_operation.yaml
- tests/data/trainercontroller/loss_custom_operation_invalid_action.yaml
- tests/data/trainercontroller/loss_invalid_metric.yaml
- tests/data/trainercontroller/loss_invalid_operation.yaml
- tests/data/trainercontroller/loss_invalid_operation_action.yaml
- tests/data/trainercontroller/loss_invalid_trigger.yaml
- tests/data/trainercontroller/loss_on_threshold.yaml
- tests/data/trainercontroller/loss_on_threshold_with_trainer_state.yaml
- tests/data/trainercontroller/loss_unavailable_metric.yaml
- tests/data/trainercontroller/loss_with_malicious_input_rule.yaml
- tests/data/trainercontroller/loss_with_malicious_os_rule.yaml
- tests/trainercontroller/custom_operation.py
- tests/trainercontroller/custom_operation_invalid_action.py
- tuning/sft_trainer.py
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/controllermetrics/loss.py
- tuning/trainercontroller/operations/hfcontrols.py
- tuning/trainercontroller/operations/operation.py
All minor changes related to metric handling have been addressed in this PR.
Closes:
- #175 
- #176
- #177
- #188
- #189 
Run the test cases.
> feat: All metric handling changes

- tuning/trainercontroller/controllermetrics/__init__.py
- tuning/trainercontroller/controllermetrics/metrics.yaml
- tuning/trainercontroller/controllermetrics/per_process_state.py
Adds a metric that exposes per process state to the trainer controller.
https://github.com/foundation-model-stack/fms-hf-tuning/issues/181
`make test`
> feat: per process state metric

- build/Dockerfile
Add a dockerfile argument to enable aimstack
NA
Run with a dockerfile built with and without the argument `ENABLE_AIM`
Tested the PR with both scenarios, `ENABLE_AIM` does not set and `ENABLE_AIM=true`
Tested without `ENABLE_AIM` argument
```
[dushyantbehl@experimentsplatform fms-hf-tuning]$ docker build -t fms-hf-tuning:dev . -f build/Dockerfile
[+] Building 562.1s (30/30) FINISHED                                                                                                                                                                                                           docker:default
=> [internal] load build definition from Dockerfile …
```
> feat: Add a dockerfile argument to enable aimstack

- tests/utils/test_config_utils.py
- tuning/config/peft_config.py
Original issue (from Slack):
> By default target_modules None should work, and it will use the default values [HF has here](https://github.com/huggingface/peft/blob/7b1c08d2b5e13d3c99b7d6ee83eab90e1216d4ba/src/peft/utils/constants.py#L70) for each architecture when not specified  . In [PEFT LoraConfig](https://huggingface.co/docs/peft/en/package_reference/lora#peft.LoraConfig) default is None.
> In our Config also we should set it to None in [tuning/config/peft_config.py](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/tuning/config/peft_config.py#L48) and ensure it still works with None through unit tests.
In short, changed
`default_factory=lambda: ["q_proj", "v_proj"],` to `default=None,` in the LoraConfig class.
N/A
Run unit tests.
Additionally, you can run tuning on …
> Set default value of target_modules to be None in LoraConfig

- tests/build/test_launch_script.py
- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/sft_trainer.py
When custom tokenizer is provided, the flow that adds special tokens to the tokenizer should be skipped. 
Added one unit test.
> fix: do not add special tokens for custom tokenizer

- .github/workflows/build-and-publish.yaml
- .github/workflows/image.yaml
Running out of space on PR test Image / build. Github workers are granted 20GB and our dependencies exceed this.
```
System.IO.IOException: No space left on device : '/home/runner/runners/2.317.0/_diag/Worker_20240802-144345-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
at …
```
> Add functionality to free disk space from Github Actions

- tests/build/test_launch_script.py
- tests/test_sft_trainer.py
Add unit test for recent change (PR #269) to verify that HF library correctly changes target_modules to the default values.
Run unit tests.
> Add unit test to verify target_modules defaults correctly

- tuning/sft_trainer.py
- tuning/trackers/aimstack_tracker.py
Ensure additional metadata to trackers will not throw errors in happy case.
Fixes #289 
Verified 
```
(.fms-hf-tuning-venv) ➜  fms-hf-tuning git:(fix-bad-value-error) ✗ accelerate launch \
--main_process_port 1234 \
--config_file /home/schrodinger/workspace/ibm/fms-hf-tuning/fixtures/accelerate_fsdp_defaults.yaml \
--num_processes 2 \
-m tuning.sft_trainer \
--model_name_or_path "Maykeye/TinyLLama-v0" \
--training_data_path "/home/schrodinger/bin/twitter_complaints.json" \
--output_dir /home/schrodinger/bin/output/tiny-llama-ft-multigpu \
--num_train_epochs 5 \
--per_device_train_batch_size 4 \
--gradient_accumulation_steps 4 \
--per_device_eval_batch_size 4 \
--learning_rate 0.000001 \
--use_flash_attn no \
--response_template "\n### Label:" \
--dataset_text_field "output" \
--tracker …
```
> Ensure additional metadata to trackers don't throw error in happy case.

- tuning/trackers/aimstack_tracker.py
Fixes a bug where multiple runid were being created with accelerate.
Before - 
After - 
N/A
> fix: multiple runid creation bug with distributed training

- examples/trainercontroller_configs/log_controller.yaml
- tests/data/trainercontroller/__init__.py
- tests/data/trainercontroller/log_controller.yaml
- tests/data/trainercontroller/loss_on_threshold_with_trainer_state.yaml
- tests/data/trainercontroller/loss_with_invalid_type_rule.yaml
- tests/data/trainercontroller/on-save.yaml
- tests/trainercontroller/test_tuning_trainercontroller.py
- tuning/trainercontroller/callback.py
- tuning/trainercontroller/controllermetrics/trainingstate.py
- tuning/trainercontroller/operations/__init__.py
- tuning/trainercontroller/operations/logcontrol.py
- tuning/trainercontroller/operations/operation.py
Logging control operation to inject logs into the training loop.
"Closes #179"
Use the following trainer controller configuration to try out the logging control:
```
controller_metrics:
- name: state
class: TrainingState
operations:
- name: logcontrolstep
class: LogControl
arguments:
log_format: 'This is a test log format [{event_name}] => {tc_metrics[state]}'
log_level: warning
controllers:
- name: log-controller-step
triggers:
- on_step_end
rule: 'True'
operations:
- logcontrolstep.should_log
```
> feat: logging control operation

- tuning/trainercontroller/callback.py
Some events like on_step_begin, on_optimizer_step, on_substep_end have been added to the trainer controller callback.
By using the events in the trainer controller configuration as `trigger`. For example:
```
controller_metrics:
- name: trainer_state
class: TrainingState
controllers:
- name: stop_on_training_loss_on_save
triggers:
- on_optimizer_step
rule: trainer_state["epoch"] >= 0.5
operations:
- hfcontrols.should_training_stop
```
> feat: Added additional events such as on_step_begin, on_optimizer_step, on_substep_end

- build/Dockerfile
I'm noticing a high security vulnerability with setuptools.  
severityCHML | cvss | riskFactors | cve | link | hasFix | status | packageType | packageName | packageVersion | packageLicense | packageBinaryPkgs | packagePath
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
H | 8.8 | Attack complexity: low,Attack vector: network,DoS - High,Has fix,High   severity,Recent vulnerability,Remote execution | CVE-2024-6345 | https://nvd.nist.gov/vuln/detail/CVE-2024-6345 | Y | fixed in 70.0.0 | python | setuptools | 65.5.1 |   |   | /usr/local/lib/python3.11/site-packages/setuptools-65.5.1.dist-info
So I'm adding a line to the DockerFile to force an update to setuptools.
Closes 1176
https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1176
I clone my branch:
```
git …
```
> Always update setuptools to latest

- examples/trainercontroller_configs/logging_controller_with_rank.yaml
This PR introduces a more involved example for log controller which uses multiple trainer controller metrics.
Closes #264
> feat: Example log controller yaml with training state

- tests/test_sft_trainer.py
- tuning/sft_trainer.py
Bug where log level set in `save()` fails if lowercase values passed in for log_level. This fixes the issue and adds a small addition to unit tests to ensure this change fixes it.
> fix: setting log level in save()

- tuning/config/configs.py
- tuning/data/tokenizer_data_utils.py
Defaults multiple to 1 thereby not resizing the embedding unless user wishes to resize it by explicitly using this feature. 
Motivation is to support vLLM inference for LoRA which needs merging of adapter when embedding layer is resized with no real tokens. Findings from @Ssukriti  and team.
> fix: do not resize embedding layer by default

- tuning/sft_trainer.py
Fixes https://github.com/foundation-model-stack/fms-hf-tuning/issues/307
https://github.com/foundation-model-stack/fms-hf-tuning/issues/307
```
python3 -m tuning.sft_trainer --output_dir foo --use_flash_attn false --bnb_qlora true
```
> fix: logger is unbound error

- build/Dockerfile
Changed the casing of the keyword `as` to `AS` in the Dockerfile.
Fixes https://github.com/foundation-model-stack/fms-hf-tuning/issues/319
Build the docker image as recommended in the `build/README.md`
> fix: warnings about casing when building the Docker image

- tests/test_sft_trainer.py
- tuning/sft_trainer.py
Fix test failure
Fixes https://github.com/foundation-model-stack/fms-hf-tuning/pull/324#issuecomment-2322823510
`make test`
> fix: need to pass skip_prepare_dataset for pretokenized dataset due to breaking change in HF SFTTrainer

- pyproject.toml
Add protobuf v5.28.0 to fms-hf-tuning for compatibility with certain models
> deps: Add protobuf to support ALLaM models

- pyproject.toml
v0.34.0 and v0.34.1 of accelerate has a bug where when training with FSDP, the weight is being flattened and is unable to be loaded. Capping at v0.33 before the change went in and at a verified point.
> dep: cap transformers version due to FSDP bug

- build/Dockerfile
- build/accelerate_launch.py
Removal of [lm_head hack](https://github.com/foundation-model-stack/fms-hf-tuning/pull/258) which was made to fix lm_head issue and now fixed with newer vllm versions, the [change](https://github.com/vllm-project/vllm/pull/6758) coming in as of v0.5.4 
[#1166](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1166)
Running LoRA and full fine tuning of granite-3b and llama-8b model without removal of lm_head able to run inference on.
> fix: remove lm_head post processing

- tuning/sft_trainer.py
For any model when tokenizer has PAD token equal to EOS token, then the `DataCollatorForCompletionOnlyLM` masks the EOS token from `labels` of dataset batch which leads to repetitive `predicted_target` during inference time thus decreasing f1-micro for models like `granite-34b-gptq` 
[#1309 ](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1309)
Running HF inference after QLoRA tuning of `granite-34b-gptq` model.
> fix: Addition of default pad token in tokenizer when EOS and PAD token are equal

- README.md
- tests/acceleration/spying_utils.py
- tests/acceleration/test_acceleration_dataclasses.py
- tests/acceleration/test_acceleration_framework.py
- tests/test_sft_trainer.py
- tuning/config/acceleration_configs/__init__.py
- tuning/config/acceleration_configs/acceleration_framework_config.py
- tuning/config/acceleration_configs/attention_and_distributed_packing.py
- tuning/config/acceleration_configs/fused_ops_and_kernels.py
- tuning/config/acceleration_configs/instruct_lab_config.py
- tuning/sft_trainer.py
This PR adds two dataclass arguments to enable *padding free* and *multipack* for the `sft_trainer.py`, via the new `fms acceleration` [attention-and-distributed-packing](https://github.com/foundation-model-stack/fms-acceleration/tree/main/plugins/attention-and-distributed-packing) plugin and allows the current `--fastkernels` dataclass to support optimized full-finetuning:
-  `--padding_free`: technique to process multiple examples in single batch without adding padding tokens that waste compute.
-  `--multipack`: technique for *multi-gpu training* to balance out number of tokens processed in each device, to minimize waiting time.
- `--fast_kernels`: Previously limited only for QPEFT (used to raise if not activated with `--fast_lora`), Now allows for optimized full/standard LoRA …
> feat: Add DataClass Arguments to Activate Padding-Free and MultiPack Plugin and FastKernels

- README.md
- scripts/post_process_adapters_vLLM.py
- tests/build/test_launch_script.py
- tests/test_sft_trainer.py
- tuning/data/tokenizer_data_utils.py
- tuning/sft_trainer.py
- tuning/utils/merge_model_utils.py
> feat: Refactor post-processing of adapters

- pyproject.toml
Latest version of [transformers v4.45.0](https://github.com/huggingface/transformers/releases) was released two hours ago and is breaking unit tests ([see failures](https://github.com/foundation-model-stack/fms-hf-tuning/actions/runs/11040215549/job/30667675308?pr=338)) with error: `AttributeError: 'AdamW' object has no attribute 'train'` when running training. 
Capping version below v4.45.
> fix: cap transformers at v4.44

- build/accelerate_launch.py
Addition of code to create `output_dir` in `accelerate_launch.py` if it doesn't exist.
[#1352](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1352)
Run full fine tuning or LoRA tuning with multiple GPUs and check if issue exists.
> fix: unable to find output_dir in multi-GPU during resume_from_checkpoint check

- tuning/utils/merge_model_utils.py
Some granite models use naming convention `wte.weight` instead of `embed_tokens.weight`. Accounting for the difference for v2.0.0 release until we can get something more generic.
> fix: check for wte.weight along with embed_tokens.weight

- pyproject.toml
Previousl in PR #329 we had hardcoded release branch to be v0.9.6 of trl but we want to unset the hardcoded version to get updates since we fixed the error with pretokenized datasets on main branch.
> build(deps): unset hardcoded trl version to get latest updates

- .github/workflows/format.yml
- .github/workflows/image.yaml
- .github/workflows/test.yaml
We want to run CI automation on PRs that go directly to release branch. This includes any patch fixes (currently) and the release time PRs. By not running unit tests, we miss differences between main and release branch as well as dependencies may be new and updated that should be tested. This vets the PR at release time.
> ci: run unit tests, fmt, image build on release branch

- tuning/sft_trainer.py
Fixes crash in https://github.com/foundation-model-stack/fms-hf-tuning/issues/359
https://github.com/foundation-model-stack/fms-hf-tuning/issues/359
Run a multi GPU training with a non-existent output dir.
> fix: crash when output directory doesn't exist

- fixtures/accelerate_fsdp_defaults.yaml
- pyproject.toml
- tests/build/dummy_job_config.json
- tests/build/test_utils.py
Updates the requirements on [accelerate](https://github.com/huggingface/accelerate) to permit the latest version.
Accelerate version 1.0.0 [release notes](https://github.com/huggingface/accelerate/releases/tag/v1.0.0)
Variable `--fsdp_backward_prefetch_policy` became outdated, replaced with new variable `--fsdp_backward_prefetch` to fix unit tests.
closes #372
> build(deps): Upgrade accelerate requirement to allow version 1.0.0

- build/Dockerfile
Add triton environment variables for QLoRA tuning if random user in cluster.
closes #367 
Use image `docker-na-public.artifactory.swg-devops.com/wcp-ai-foundation-team-docker-virtual/sft-trainer:triton_env_vars_ubi9_py311.triton_env_vars` and run tuning as a random user without setting these variable manually.
> build: Set triton environment variables

- pyproject.toml
Reported issue with building FA2 with latest torch 2.5 that came out yesterday morning. Thus will cap torch below 2.5.
> build(deps): torch<2.5 due to FA2 error with new version

- pyproject.toml
The triton fast_kernels are broken in transformers v4.46 due to the changes and the way the patching is done in fms-acceleration described [here](https://github.com/foundation-model-stack/fms-acceleration/issues/98). In addition, the  gradient_accumulation is deteriorated in v4.46 which is fixed in [transformers PR](https://github.com/huggingface/transformers/pull/34373) which has been merged but not released yet.
In addition, upgrading transformers broke unit tests and is being resolved/discussion in #383.
Thus we will set transformers below v4.46 while we wait for these fixes to go in.
> build(deps): set transformers below 4.46, waiting on fixes

- architecture_records/004-datapreprocessor.md
This PR adds an ADR for the newly proposed changes to the data pre procesor implementation in fms-hf-tuning.
> docs: Data Preprocessor ADR

- tests/artifacts/predefined_data_configs/__init__.py
- tests/artifacts/predefined_data_configs/apply_custom_template.yaml
- tests/artifacts/predefined_data_configs/multiple_datasets_with_sampling.yaml
- tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking.yaml
- tests/data/test_data_preprocessing_utils.py
- tuning/data/data_config.py
- tuning/data/data_processors.py
> feat: Perform dataset mixing via sampling probabilities in data config

- tests/test_sft_trainer.py
- tuning/data/data_processors.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
Add an argument in train to take in any user specified data handlers to be registered with the data preprocessor which can be invoked by a custom data config for advanced users.
> feat: Expose additional data handlers as an argument in train

- tuning/sft_trainer.py
There was spread of information in multiple variables, therefore confining the source of truth to a single variable, preferably with dataclass objects in this scenario.
cc: @dushyantbehl
> fix: update dataclass objects directly instead of creating new variables

- .gitignore
- README.md
- build/Dockerfile
- docs/experiment-tracking.md
- pyproject.toml
- tests/test_sft_trainer.py
- tests/trackers/test_aim_tracker.py
- tests/trackers/test_mlflow_tracker.py
- tuning/config/tracker_configs.py
- tuning/sft_trainer.py
- tuning/trackers/aimstack_tracker.py
- tuning/trackers/mlflow_tracker.py
- tuning/trackers/tracker_factory.py
This code change integrates MLflow tracker backed via the existing `tracker` api in `fms-hf-tuning`
Closes https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1495
TBA
> feat: Integrate MLflow tracker

- README.md
- docs/advanced-data-preprocessing.md
> docs: Add documentation for data preprocessor release

- README.md
- tests/test_sft_trainer.py
- tuning/data/data_handlers.py
- tuning/data/data_processors.py
Recent commit https://github.com/foundation-model-stack/fms-hf-tuning/commit/d7f06f5fc898eb700a9e89f08793b2735d97889c introduced support for hf dataset id inside `data_config` but the code had a minor fix needed to support hf dataset id being passed via `training_data_path`.
With this patch code now supports hf dataset id via `training_data_path` argument.
Tested with an hf dataset and added a unit test for the same.
> feat: Allow hf dataset id to be passed via training_data_path

- .github/workflows/image.yaml
- tests/data/test_data_preprocessing_utils.py
- tuning/config/acceleration_configs/attention_and_distributed_packing.py
- tuning/data/data_preprocessing_utils.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
Closes #426
Add support for using padding free plugin without response template.
Fixes #427
> feat: allow for padding free plugin to be used without response template 

- tests/acceleration/test_acceleration_framework.py
- tuning/sft_trainer.py
Nit fix for function in fms-acceleration which needs to be changed in fms-hf-tuning as well.
[PR #118](https://github.com/foundation-model-stack/fms-acceleration/pull/118) in fms-acceleration should be merged at the same time.
> fix: function name from `requires_agumentation` to `requires_augmentation`

- tuning/sft_trainer.py
Add `pad_token` to special_tokens_dict when `pad_token == eos_token`
Issue:https://github.com/foundation-model-stack/fms-hf-tuning/pull/343
Issue 343 modifies pad_token of tokenizer but in this PR adds it to `special_tokens_dict` for model resizing. 
Reason of this case of `pad_token == eos_token`: 
When tokenizer has PAD token equal to EOS token, then the DataCollatorForCompletionOnlyLM masks the EOS token from labels of dataset batch and hence its not used in loss calculation and hence it leads to repetitive `predicted_target` during inference time.
> fix: Add pad_token to special_tokens_dict when pad_token == eos_token

- README.md
docs update to clarify EOS token support for different types of datasets
> docs: EOS token support

- build/Dockerfile
- pyproject.toml
- tests/build/test_launch_script.py
- tests/test_sft_trainer.py
- tests/trackers/test_hf_resource_scanner_tracker.py
- tuning/config/tracker_configs.py
- tuning/sft_trainer.py
- tuning/trackers/hf_resource_scanner_tracker.py
- tuning/trackers/tracker_factory.py
Extracted from this [suggestion](https://github.com/foundation-model-stack/fms-hf-tuning/pull/397#issuecomment-2537828610) in a prior PR, adding [HFResourceScanner](https://github.com/foundation-model-stack/hf-resource-scanner) TrainerCallback as a tracker.
In order to use this, user would need to install `HFResourceScanner` in the environment, and pass in training args to enable:
```
"trackers": ["hf_resource_scanner"]
"scanner_output_filename": "scanner_output.json" // optional, if not passed, the default value is used
```
See the test written in `test_launch_script.py`
> feat: add scanner tracker

- README.md
With changes to data preprocessor, file extension is now required for data files because of the variety of datasets we support (as opposed to just supporting JSON, which made it so file extension wasn't required because it could be assumed).
> docs: add note to note that file extension is required in training data path

- tuning/trackers/aimstack_tracker.py
Fix bug in conditional check where aimstack server tracking was not picked up correctly.
Tested by running a KFTO job with aimstack tracker server url and port.
> fix: bug in aim tracker where the server based tracking was not picked

- README.md
> fix: space missing from data_formatter_template causing mismatch with response_template

- tests/data/test_data_handlers.py
- tuning/data/data_handlers.py
Modification as a part of this PR: https://github.com/foundation-model-stack/fms-hf-tuning/pull/438
Includes usage of `Sandboxed Environment` instead of normal `Environment` in rendering Jinja template which is more safer to use as it evaluates untrusted templates and restricts access to unsafe attributes/methods inside the template. 
Issue: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1470
Check relevant test case.
> fix: Using Sandboxed Environment in handler rendering Jinja template

- tests/data/test_data_preprocessing.py
- tuning/data/data_handlers.py
Handler `tokenize_and_apply_input_masking` [here](https://github.com/foundation-model-stack/fms-hf-tuning/blob/381fdd55d42d2fffbf8ef0ed53d55bfe83373924/tuning/data/data_handlers.py#L55), couldn't read `tokenizer_kwargs` due to incorrect retrieval from [tokenizer_kwargs passed to this handler](https://github.com/foundation-model-stack/fms-hf-tuning/blob/381fdd55d42d2fffbf8ef0ed53d55bfe83373924/tuning/data/data_handlers.py#L61) when applying map [here](https://github.com/foundation-model-stack/fms-hf-tuning/blob/381fdd55d42d2fffbf8ef0ed53d55bfe83373924/tuning/data/data_processors.py#L287).
Issue: https://github.com/foundation-model-stack/fms-hf-tuning/issues/464
> fix:Retrieval of tokenizer_kwargs in data handler tokenize_and_apply_input_masking

- docs/advanced-data-preprocessing.md
- docs/ept.md
- tests/artifacts/predefined_data_configs/__init__.py
- tests/artifacts/predefined_data_configs/rename_retain_columns.yaml
- tests/data/test_data_preprocessing.py
- tests/test_sft_trainer.py
- tuning/data/data_config.py
- tuning/data/data_processors.py
Add two flags to the `data_config` under `dataset` definition. 
1. `rename_columns` which allows users to rename columns by passing a dict
2. `retain_columns` which allows users to specify which columns to retain and drop others.
This is different and outside the `remove_columns` argument to `data handlers` because people might want to use this functionality even without invoking data handlers.
This is especially needed in the case of interleaving multiple datasets with different features.
> feat: Add support for renaming and retaining columns in data preprocessor

- tests/test_sft_trainer.py
- tuning/config/configs.py
- tuning/sft_trainer.py
Adds support for add_special_tokens to tokenizer's vocabulary via cli args
List of Special Tokens can be passed as follows:
Partially Solves #470 , Support for Reserved Special Tokens is not supported yet
Run a small sample training job with `--add_special_tokens` flag 
```
python tuning/sft_trainer.py    --include_tokens_per_second="true" \
--learning_rate="1e-05" \
--logging_steps="1" \
--logging_strategy="steps" \
--max_steps="100" \
--model_name_or_path="/your/model" \
--output_dir="/output/directory" \
--per_device_train_batch_size="1" \
--save_steps="50" \
--save_strategy="steps" \
--add_special_tokens "<|assistant|>" "<|user|>" \
--use_flash_attn=false \
--training_data_path="/dataset"
```
once the training is completed load the trained model and check if the special token is …
> feat: Support for add special tokens via cli args

- docs/advanced-data-preprocessing.md
- tests/artifacts/predefined_data_configs/__init__.py
- tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template.yaml
- tests/test_sft_trainer.py
- tuning/data/data_config.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
Adds support for `chat_template`/`chat_template_b64` from data config.
adds fix for "/n" parsing issue for passing chat_template via cli args
Updates test case for chat_template through data config
> feat: add support for chat template from data config

- README.md
- tests/test_sft_trainer.py
- tuning/config/acceleration_configs/__init__.py
- tuning/config/acceleration_configs/callbacks.py
- tuning/config/acceleration_configs/fast_moe.py
- tuning/sft_trainer.py
This is to support automatic HF checkpointing for moe EP training runs using fms-acceleration.
Depends on https://github.com/foundation-model-stack/fms-acceleration/pull/133
#480
> feat: support moe hf chkpt

- tuning/data/data_processors.py
TRL made a [change in the code](https://github.com/huggingface/trl/pull/3106) where they shifted to using `main_process_first` instead of `local_main_process_first` as the later can cause race conditions among nodes and lead to cache `FileNotFoundErrors` these were also reported internally by few users [here](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1666). 
Might be worthwile to be conservative for now and follow the same pattern.
Closes  [#1666](https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1666)
> fix: Use main process first instead of local_main_process_first

- tests/test_sft_trainer.py
- tuning/config/acceleration_configs/fast_moe.py
- tuning/sft_trainer.py
Building on PR #486, saving `hf_converted_checkpoint` to `save_model_dir` if it exists.
> fix: save model dir hf moe checkpoint

- pyproject.toml
Installing mamba_ssm from github blocks PyPi release due to error
```
[33mWARNING [0m Error during upload. Retry with the --verbose option for more details. 
2025-03-20T15:47:26.0222991Z [31mERROR   [0m HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
Can't have direct dependency: mamba_ssm[causal-conv1d]@                
git+https://github.com/state-spaces/mamba.git ; extra == "mamba". See  
https://packaging.python.org/specifications/core-metadata for more     
information.      
```
Thus we are installing from package instead of github.
> build(deps): install mamba_ssm from package instead of github

- README.md
- tests/test_sft_trainer.py
- tuning/config/acceleration_configs/fast_moe.py
- tuning/config/acceleration_configs/utils.py
New interface for `--fast_moe` to support kernels only mode.
- `--fast_moe` takes either an integer or boolean value.
- When its an integer it enables expert parallel sharding with the given expert parallel degree along with Scatter MoE kernels.
- When its boolean False, it is Scatter MoE Kernels with complete replication of experts across ranks.
- When its boolean True, it is Scatter MoE Kernels with experts sharded based on the top level sharding protocol (e.g. FSDP).
You can check the unit tests.
Tested with unit tests.
> feat: new interface for fast_moe (non breaking)

- scripts/offline_data_processing.py
- tests/utils/test_embedding_resize.py
- tuning/utils/tokenizer_data_utils.py
While adding additional special tokens it was noticed that the existing special tokens were being replaced and not present this was due to the fact that when calling [add_special_tokens](https://huggingface.co/docs/transformers/en/main_classes/tokenizer#transformers.PreTrainedTokenizerFast.add_special_tokens) the argument [replace_additional_special_tokens](https://huggingface.co/docs/transformers/en/main_classes/tokenizer#transformers.PreTrainedTokenizerFast.add_special_tokens.replace_additional_special_tokens) was being set to `True` by default and was causing the issue. 
*Note* the HF [documentation](https://github.com/huggingface/transformers/blob/0b057e66b52556da3a1cbc29e2a98c0784ea9c33/src/transformers/tokenization_utils_base.py#L932) of this function states 
```
If `True`, the …
```
> fix: additional special tokens being replaced

- pyproject.toml
HF recently made a [patch available](https://github.com/huggingface/transformers/pull/36991) in transformers which looks to be a breaking change for anyone looking to load a model from checkpoint.
```
except RuntimeError as e:
>                           raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
E                           _pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options 
E                               (1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
E                               (2) Alternatively, to load with `weights_only=True` please check the recommended steps in …
```
> fix: downgrade transformers due to breaking change in loading from checkpoint.

- tuning/config/configs.py
> fix: (data pre-process) un-escape templates and strings passed on cli correctly

- tests/artifacts/predefined_data_configs/__init__.py
- tests/artifacts/predefined_data_configs/mt_data_granite_3_1B_tokenize_and_mask_handler.yaml
- tests/test_sft_trainer.py
- tuning/data/data_handlers.py
- tuning/data/data_preprocessing_utils.py
This commit adds OpenInstruct data handler for chat style training which performs masking outside of DataCollatorForCompletionOnlyLM and internally switches to DataCollatorForSeq2Seq.
> feat: Add OI style data handler for chat template usecase

- tuning/sft_trainer.py
Setting use_cache to false when gradient checkpointing is true. If not, then `modeling_granite`/`llama` has a check to set it to false anyway but after printing the following warning:
```
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
```
This is causing a graph break when doing torch.compile. To avoid this, we are manually setting this arg when loading model, [similar to how SFT is doing in their example scripts](https://github.com/huggingface/trl/blob/9f3702f6be24505c58aadbbf8651b24ef10363b6/trl/scripts/sft.py#L80C15-L80C16)
Example tuning command to reproduce the error:
```
accelerate launch --num_processes=1  -m tuning.sft_trainer --output_dir ./train_output --max_steps 5 --learning_rate 2e-5 --training_data_path=/data/cg/ei_5.jsonl …
```
> fix: set use_cache=false while model loading to prevent graph break

- tuning/config/configs.py
- tuning/sft_trainer.py
Change the default model_name_or_path from "facebook/opt-125m" to None
This is especially relevant when using the offline dataset processing script where it's easy to forget to specify the model_name_or_path
> fix: change the default model_name_or_path from "facebook/opt-125m" to None

- README.md
- tuning/sft_trainer.py
Fix for supporting vision model tuning.
Changes:
- Removal of `use_cache` from `AutoModelForVision2Seq.from_pretrained` as vision model of type (`MllamaForConditionalGeneration`, `LlavaForConditionalGeneration` and `LlavaNextForConditionalGeneration`) doesn't support it.
- ReadMe update to include LoRA tuning support of vision models.
Issue: https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1610
> fix:Remove use_cache and update ReadMe.

- build/Dockerfile
Use `no-build-isolation` so mamba's build requirements do not interfere with our library's during image build process
> ci: use --no-build-isolation flag for mamba

- build/Dockerfile
We saw failure at this step:
```
> [cuda-base 1/1] RUN dnf config-manager        --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo     && dnf install -y         cuda-cudart-12-1-12.1.55-1         cuda-compat-12-1-530.30.02-1     && echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf     && echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf     && dnf clean all:
#0 0.219 No such command: config-manager. Please use /usr/bin/dnf --help
#0 0.219 It could be a DNF plugin command, try: "dnf install 'dnf-command(config-manager)'"
```
Unsure why this started failing when it was working before. But this PR will fix it by installing `dnf-plugins-core`
> ci: Install dnf-plugins-core in cuda-base stage

- tuning/sft_trainer.py
Incorrect check leading to unnecessary lora checks to non fast moe runs. Introduced in https://github.com/foundation-model-stack/fms-hf-tuning/pull/530
> fix: incorrect check on fast moe activation

- tuning/sft_trainer.py
Goes with [#142](https://github.com/foundation-model-stack/fms-acceleration/pull/142) to allow `all-linear` for ScatterMoE. Without the fms-acceleration PR to filter it out, router was included since it is a linear layer, but will not be able to run vLLM inference if it is included. With the fms-acceleration PR, `all-linear` can be passed because `router` will always be filtered out
> fix: fastmoe lora `all-linear` excluding `router`

- README.md
- pyproject.toml
- scripts/run_inference.py
- tests/test_sft_trainer.py
- tuning/config/peft_config.py
- tuning/data/setup_dataprocessor.py
- tuning/sft_trainer.py
- tuning/utils/config_utils.py
- tuning/utils/import_utils.py
Support for activated lora. Right now points to alora code on a public repo https://github.com/IBM/activated-lora . Also uses a data collator by default due to the nature of alora, and adds a new argument for the invocation string. Also note that peft=0.14.0 seems to be necessary to avoid errors with the alora code.
https://github.ibm.com/ai-foundation/watson-fm-stack-tracker/issues/1629
I tested it with the following command
python tuning/sft_trainer.py \
--model_name_or_path ibm-granite/granite-3.1-2b-base \
--training_data_path /proj/dmfexp/statllm/users/kgreenewald/Thermometer/TuningStack/fms-hf-tuning-alora/tests/artifacts/testdata/json/twitter_complaints_input_output.json \
--output_dir ./output \
--num_train_epochs 1 \
--per_device_train_batch_size 4 \
---learning_rate 1e-4 \ …
> feat: Add ALoRA support

- tests/data/test_data_preprocessing.py
- tuning/data/setup_dataprocessor.py
Added error handling for the dataset splitting and streaming configurations in the `process_dataargs` flow. Specifically:
- Raise `ValueError` if `eval_strategy` is set to anything other than `"no"` but no evaluation dataset is provided.
- Raise `ValueError` if `padding_free` is enabled while streaming is also enabled, which is not supported.
N/A
- Try setting `eval_strategy="epoch"` or `"steps"` without providing an eval set → should raise an error.
- Try enabling `padding_free=huggingface` while using streaming dataset → should raise an error.
added screenshot for Error handling when train_set is None using the attached dataconfig:
```
dataprocessor:
type: default
sampling_stopping_strategy: first_exhausted
seed: 66
datasets:
- name: dataset_1
split:
train: 0.0
validation: 1.0
sampling: …
```
> feat: add error handling for split dataset feat

- tests/artifacts/predefined_data_configs/pretokenized_data.yaml
- tuning/data/data_config.py
if no `datapreprocessor` is provided in data config then the data pre processor fails with an error rather than falling back to default...this change fixes that.
> fix: use default dataprocessor if one is not provided

- tuning/sft_trainer.py
With the experimental Trainer Controller changes in https://github.com/foundation-model-stack/fms-hf-tuning/pull/558 the `data processing only` mode was broken and it failed with an error due to missing argument even though the execution was correct. 
This patch fixes that.
Before - 
```
(.python3.12-venv) ➜  checkpoint rm -rf /tmp/test-train && python3 -m tuning.sft_trainer \
--model_name_or_path "/Volumes/Projects/Projects/ai-platform-engg/granitebuild/checkpoint/basemodel/" \
--output_dir /tmp/test-train/ \
--use_flash_attn False \
--do_dataprocessing_only --num_train_dataset_shards 1 --data_config /Volumes/Projects/Projects/ai-platform-engg/finetuning-defense/data_config.yml
Rank-0 [INFO]:sft_trainer.py:main: fms-hf-tuning execution start
Rank-0 [INFO]:sft_trainer.py:main: 
.... …
```
> fix: data processing job exiting with failure even though successful

- tuning/config/configs.py
- tuning/sft_trainer.py
Sets the `use_cache=False`, disabling the model's KV cache while fine-tuning the model.
Solves https://github.com/huggingface/transformers/issues/39795 for our stack.
--
Since this was a bug fix, I have tested multiple settings of the flags to verify that the memory usage has dropped for FSDP+LoRA use case.
In my toy example, with 4 GPUs on an 8b model with BF16 datatype, memory dropped from 28GB per GPU to 12GB per GPU.
> fix: Disable caching in transformers via `use_cache` flag to avoid unncessary memory overhead

- tuning/trainercontroller/controllermetrics/per_process_state.py
The rank is set to zero when the distributed mode is not initialized.
Use **accelerate** and this trainer controller [configuration](https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/examples/trainercontroller_configs/logging_controller_with_rank.yaml). The info log should show the Rank to 0 when a single-gpu is used.
> fix: Rank is set to zero by default
